# Generated by Django 4.2.16 on 2024-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Shipping_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping_charge',
            field=models.DecimalField(decimal_places=0, default='55', max_digits=7),
            preserve_default=False,
        ),
    ]
