# Generated by Django 4.2.16 on 2024-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_order_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Shipping_charge',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=7),
        ),
    ]
