# Generated by Django 4.2.16 on 2024-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Not_Completed', 'Not Completed'), ('Success', 'Success'), ('Failed', 'Failed')], default='Not_Completed', max_length=20),
        ),
    ]
