# Generated by Django 4.2.16 on 2024-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_paymentrecord_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], max_length=20),
        ),
    ]
