# Generated by Django 4.2.16 on 2024-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='processing_time',
            new_name='received_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Abandoned', 'Order Abandoned'), ('Order Received', 'Order Received'), ('Order Confirmed', 'Order Confirmed'), ('Product Shipped', 'Product Shipped'), ('Product Delivered', 'Product Delivered')], default='Order Abandoned', max_length=20),
        ),
    ]
