# Generated by Django 4.2.16 on 2024-12-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_rename_processing_time_order_received_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='received_time',
            new_name='placed_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Abandoned', 'Order Abandoned'), ('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Product Shipped', 'Product Shipped'), ('Product Delivered', 'Product Delivered')], default='Order Abandoned', max_length=20),
        ),
    ]
