# Generated by Django 4.2.16 on 2024-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_rename_received_time_order_placed_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='payment_success',
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('payment successful', 'payment successful'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], max_length=20),
        ),
    ]
