# Generated by Django 4.2.18 on 2025-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_rename_complete_order_payment_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(default='not mentioned.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='not mentioned.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('Payment Successful', 'Payment Successful'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=20),
        ),
    ]
