# Generated by Django 4.2.18 on 2025-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_product_age_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
